FROM node:18 as dependencies
LABEL maintainer="Felipe Bogaerts de Mattos"

WORKDIR /frontend

COPY . .
RUN npm install --frozen-lockfile

ENV NODE_ENV=development

EXPOSE 3000
ENTRYPOINT ["yarn", "dev"]