services:
  app:
    build:
      context: ./acordes
      dockerfile: Dockerfile.dev
    container_name: a-cordes-app
    ports:
      - "3000:3000"
    environment:
      - WDS_SOCKET_PORT=0
    volumes:
      - ./acordes/:/usr/app/
