version: "3.9"

services:
  nginx:
    build:
      context: ./nginx/
      dockerfile: Dockerfile.dev
    restart: always
    container_name: a-cordes-nginx
    ports:
      - "8000:80"
    depends_on:
      - backend
      - frontend
  backend:
    build: 
      context: ./a_cordes/
      dockerfile: Dockerfile
    container_name: a-cordes-backend
    volumes:
      - ./a_cordes/:/usr/app/
    entrypoint: >
      bash -c "python3 manage.py migrate --no-input && 
      python3 manage.py runserver 0.0.0.0:8000"
    
  frontend:
    build: 
      context: ./frontend/
      dockerfile: Dockerfile.dev
    container_name: a-cordes-frontend
    environment:
      - WDS_SOCKET_PORT=0
    volumes:
      - ./frontend/src/:/frontend/src/
      - ./frontend/public/:/frontend/public/
