services:
  db:
    image: postgres:13.7
    container_name: acordes-db
    env_file:
      - ./.envs/.env.dev
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  app:
    build:
      context: ./acordes
      dockerfile: Dockerfile.dev
    container_name: acordes-app
    ports:
      - "3000:3000"
    environment:
      - WDS_SOCKET_PORT=0
    volumes:
      - ./acordes/src:/usr/app/src
      - ./acordes/public:/usr/app/public
      - ./acordes/node_modules:/usr/app/node_modules
      - ./acordes/package.json:/usr/app/package.json
      - ./acordes/package-lock.json:/usr/app/package-lock.json
