export const CART_ADD_ITEM_REQUEST = 'CART_ADD_ITEM_REQUEST'
export const CART_ADD_ITEM_SUCCESS = 'CART_ADD_ITEM_SUCCESS'
export const CART_ADD_ITEM_FAIL = 'CART_ADD_ITEM_FAIL'

export const CART_DELETE_ITEM_REQUEST = 'CART_DELETE_ITEM_REQUEST'
export const CART_DELETE_ITEM_SUCCESS = 'CART_DELETE_ITEM_SUCCESS'
export const CART_DELETE_ITEM_FAIL = 'CART_DELETE_ITEM_FAIL'

export const CART_GET_ALL_REQUEST = 'CART_GET_ALL_REQUEST'
export const CART_GET_ALL_SUCCESS = 'CART_GET_ALL_SUCCESS'
export const CART_GET_ALL_FAIL = 'CART_GET_ALL_FAIL'

export const CART_REMOVE_ITEM = 'CART_REMOVE_ITEM'
export const CART_SAVE_SHIPPING_ADDRESS = 'CART_SAVE_SHIPPING_ADDRESS'
export const CART_SAVE_PAYMENT_METHOD = 'CART_SAVE_PAYMENT_METHOD'
export const CART_CLEAR_ITEMS = 'CART_CLEAR_ITEMS'
