products = [
    {
    '_id': '1',
    'name': 'Violin #155',
    'image': '/images/violin155.jpg',
    'description': 'My #155 violin bow.',
    'author': 'Alysio',
    'category': 'Accessory',
    'price': 3000,
    'countInStock': 1,
    'sellerRating': 2,
    'numReviews': 10,
    },
    {
    '_id': '2',
    'name': 'Violin #156',
    'image': '/images/violin156.jpg',
    'description': 'My #156 violin bow.',
    'author': 'Alysio',
    'category': 'Accessory',
    'price': 3500,
    'countInStock': 1,
    'sellerRating': 4.5,
    'numReviews': 10,
    },
]
