apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: a-cordes-postgres-pvc
  namespace: a-cordes
spec:
  storageClassName: linode-block-storage-retain
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi