kind: PersistentVolume
apiVersion: v1
metadata:
  name: a-cordes-postgres-pv
  namespace: a-cordes
  labels:
    type: local
spec:
  storageClassName: hostpath
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/a-cordes-postgres