apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: a-cordes-postgres-pvc
  namespace: a-cordes
spec:
  storageClassName: hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  volumeName: a-cordes-postgres-pv