apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: a-cordes-postgres
  namespace: a-cordes
spec:
  serviceName: a-cordes-postgres-service
  selector:
    matchLabels:
      app: a-cordes-postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: a-cordes-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:13
          imagePullPolicy: "IfNotPresent"
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: a-cordes-secrets
                  key: A_CORDES_DATABASE_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: a-cordes-secrets
                  key: A_CORDES_DATABASE_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: a-cordes-secrets
                  key: A_CORDES_DATABASE_NAME
          ports:
          - containerPort: 5432
          volumeMounts:
          - name: a-cordes-postgres-vm
            mountPath: /var/lib/postgresql/data
      volumes:
      - name: a-cordes-postgres-vm
        persistentVolumeClaim:
          claimName: a-cordes-postgres-pvc
---
kind: Service
apiVersion: v1
metadata:
  name: a-cordes-postgres-service
  namespace: a-cordes
spec:
  selector:
    app: a-cordes-postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432