# Generated by Django 3.2.11 on 2022-05-12 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20220409_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerprofile',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
