# Generated by Django 3.2.11 on 2022-05-19 18:15

from django.db import migrations
from django.template.defaultfilters import slugify


class Migration(migrations.Migration):
    atomic = True

    def slugify_sellers(self, schema_editor):
        model = self.get_model("accounts", "SellerProfile")
        sellers = model.objects.filter(slug=None)
        for seller in sellers:
            seller.slug = slugify(seller.name)
            seller.save()

    dependencies = [
        ("accounts", "0003_alter_sellerprofile_picture"),
    ]

    operations = [migrations.RunPython(slugify_sellers)]
