# Generated by Django 3.2.11 on 2022-04-08 01:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='', max_length=10000)),
                ('category', models.CharField(blank=True, default='', max_length=255)),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=7)),
                ('count_in_stock', models.PositiveIntegerField(blank=True, default=0)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('review_count', models.PositiveIntegerField(blank=True, default=0)),
                ('image', models.ImageField(blank=True, default='products/placeholder.jpeg', upload_to='products/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seller_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.sellerprofile')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('rating', models.IntegerField(blank=True, default=0, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
