# Generated by Django 3.2.4 on 2021-12-09 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='products/placeholder.jpeg', upload_to='products/'),
        ),
    ]
