# Generated by Django 3.2.11 on 2022-05-19 16:35

from django.db import migrations
from django.template.defaultfilters import slugify


class Migration(migrations.Migration):
    atomic = True

    def slugify_products(self, schema_editor):
        model = self.get_model("products", "Product")
        products = model.objects.filter(slug=None)
        for product in products:
            product.slug = slugify(product.name)
            product.save()

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [migrations.RunPython(slugify_products)]
