# Generated by Django 3.2.11 on 2022-05-20 22:05

from django.db import migrations


class Migration(migrations.Migration):
    atomic = True

    def product_image_field_to_model(self, schema_editor):
        product_model = self.get_model("products", "Product")
        product_image_model = self.get_model("products", "ProductImage")

        all_products = product_model.objects.all()

        for product in all_products:
            product_image_model.objects.create(
                product=product, src=product.image, alt=""
            )

    def revert_product_image_field_to_model(self, schema_editor):
        product_model = self.get_model("products", "Product")
        product_image_model = self.get_model("products", "ProductImage")

        all_products = product_model.objects.all()

        for product in all_products:
            image_model = product_image_model.objects.filter(
                product=product
            ).first()
            if not image_model is None:
                product.image = image_model.src
                product.save()

    dependencies = [
        ("products", "0004_auto_20220520_2204"),
    ]

    operations = [
        migrations.RunPython(
            product_image_field_to_model,
            reverse_code=revert_product_image_field_to_model,
        )
    ]
