# Generated by Django 3.2.11 on 2022-05-20 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_image_field_to_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
