# Generated by Django 3.2.11 on 2022-09-06 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_auto_20220906_1137"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="category_old",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
