# Generated by Django 3.2.11 on 2022-09-06 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20220906_1140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category_old',
        ),
    ]
