# Generated by Django 3.2.11 on 2022-09-06 11:42

from django.db import migrations


class Migration(migrations.Migration):
    def migrate_category_to_fk(self, schema_editor):
        product_model = self.get_model("products", "Product")
        category_model = self.get_model("products", "Category")

        products = product_model.objects.all()

        for product in products:
            category = category_model.objects.get_or_create(
                name=product.category
            )
            product.category_new = category[0]
            product.save()

    def reverse_migrate_category_to_fk(self, schema_editor):
        product_model = self.get_model("products", "Product")

        products = product_model.objects.all()

        for product in products:
            category = product.category_new.name
            product.category = category
            product.save()

    dependencies = [
        ("products", "0010_product_category_new"),
    ]

    operations = [
        migrations.RunPython(
            migrate_category_to_fk,
            reverse_code=reverse_migrate_category_to_fk,
        )
    ]
