# Generated by Django 3.2.11 on 2022-09-06 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_remove_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category_new',
            new_name='category',
        ),
    ]
