# Generated by Django 3.2.4 on 2021-12-09 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='seller_profile',
        ),
    ]
