apiVersion: apps/v1
kind: Deployment
metadata:
  name: a-cordes-backend
  namespace: a-cordes
  annotations:
    config.nsm.nginx.com/default-egress-allowed: "true"
    config.nsm.nginx.com/enable-egress: "true"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: a-cordes-backend
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: a-cordes-backend
    spec:
      containers:
        - image: felipebogaertsm/a_cordes_backend@sha256:812f7cff492347d886de3980c62f03157d4707c2604eece2f458fc8cc8b93e53
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: a-cordes-secrets
          name: a-cordes-backend
          ports:
            - containerPort: 8000
              name: gunicorn
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: registry-credentials
      securityContext: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
    name: a-cordes-backend
    namespace: a-cordes
spec:
    type: ClusterIP
    selector:
        app: a-cordes-backend
    ports:
        - protocol: TCP
          port: 8000
          targetPort: 8000 # must match the deployment's port