export const ORDER_ITEM_REQUEST = "ORDER_ITEM_REQUEST"
export const ORDER_ITEM_LIST = "ORDER_ITEM_LIST"
export const ORDER_ITEM_CREATE = "ORDER_ITEM_CREATE"
export const ORDER_ITEM_UPDATE = "ORDER_ITEM_UPDATE"
export const ORDER_ITEM_DELETE = "ORDER_ITEM_DELETE"
export const ORDER_ITEM_FAIL = "ORDER_ITEM_FAIL"

export const ORDER_SHIPPING_ADDRESSES_REQUEST =
    "ORDER_SHIPPING_ADDRESSES_REQUEST"
export const ORDER_SHIPPING_ADDRESSES_LIST = "ORDER_SHIPPING_ADDRESSES_LIST"
export const ORDER_SHIPPING_ADDRESSES_CREATE = "ORDER_SHIPPING_ADDRESSES_CREATE"
export const ORDER_SHIPPING_ADDRESSES_UPDATE = "ORDER_SHIPPING_ADDRESSES_UPDATE"
export const ORDER_SHIPPING_ADDRESSES_DELETE = "ORDER_SHIPPING_ADDRESSES_DELETE"
export const ORDER_SHIPPING_ADDRESSES_FAIL = "ORDER_SHIPPING_ADDRESSES_FAIL"
