export const ORDER_SHIPPING_ADDRESSES_REQUEST =
    "ORDER_SHIPPING_ADDRESSES_REQUEST"
export const ORDER_SHIPPING_ADDRESSES_LIST = "ORDER_SHIPPING_ADDRESSES_LIST"
export const ORDER_SHIPPING_ADDRESSES_CREATE = "ORDER_SHIPPING_ADDRESSES_CREATE"
export const ORDER_SHIPPING_ADDRESSES_UPDATE = "ORDER_SHIPPING_ADDRESSES_UPDATE"
export const ORDER_SHIPPING_ADDRESSES_DELETE = "ORDER_SHIPPING_ADDRESSES_DELETE"
export const ORDER_SHIPPING_ADDRESSES_FAIL = "ORDER_SHIPPING_ADDRESSES_FAIL"
