name: à cordes CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches: 
      - master

env:
  BACKEND_IMAGE_NAME: a_cordes_backend
  FRONTEND_IMAGE_NAME: a_cordes_frontend
  TAG: latest
  DOCKER_USER: ${{ secrets.DOCKER_USER }}

jobs:
  build-backend:
    name: Build backend
    runs-on: self-hosted
    needs: 
    - super-lint
    container: docker:latest
    steps:
    - uses: actions/checkout@v3
    - name: Backend build and push
      run: |
        cd a_cordes
        docker login -u "${{ secrets.DOCKER_USER }}" -p "${{ secrets.DOCKER_PASSWORD }}"
        docker build --pull -t "${{ secrets.DOCKER_USER }}/${{ env.BACKEND_IMAGE_NAME }}:${{ env.TAG }}" \
          -t "felipebogaertsm/a_cordes_backend:${GITHUB_SHA::7}" .
        docker push ${{ secrets.DOCKER_USER }}/${{ env.BACKEND_IMAGE_NAME }}:${{ env.TAG }}

  build-frontend:
    name: Build frontend
    runs-on: self-hosted
    needs: 
    - super-lint
    container: docker:latest
    steps:
    - uses: actions/checkout@v3
    - name: Frontend build and push
      run: |
        cd frontend
        docker login -u "${{ secrets.DOCKER_USER }}" -p "${{ secrets.DOCKER_PASSWORD }}"
        docker build --pull -t "${{ secrets.DOCKER_USER }}/${{ env.FRONTEND_IMAGE_NAME }}:${{ env.TAG }}" \
          -t "${{ secrets.DOCKER_USER }}/${{ env.FRONTEND_IMAGE_NAME }}:${GITHUB_SHA::7}" .
        docker push ${{ secrets.DOCKER_USER }}/${{ env.FRONTEND_IMAGE_NAME }}:${{ env.TAG }}

  test:
    name: Testing the backend
    runs-on: self-hosted
    needs: 
    - build-backend
    - build-frontend
    container: 
      image: "felipebogaertsm/a_cordes_backend:${GITHUB_SHA::7}"
      credentials:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    steps:
    - uses: actions/checkout@v3
    - name: Testing
      run: |
        python manage.py test
  
  deploy-backend:
    name: Deploy backend
    runs-on: self-hosted
    needs: test
    container: bitnami/kubectl:latest
    env:
      NAMESPACE: a-cordes
      BACKEND_IMAGE_NAME: a_cordes_backend
      BACKEND_DEPLOYMENT_NAME: a-cordes-backend
      BACKEND_CONTAINER_NAME: a-cordes-backend
    steps:
    - uses: actions/checkout@v3
    - name: Deployment
      run: |
        kubectl -n ${NAMESPACE} set image deployment/${BACKEND_DEPLOYMENT_NAME} \
          ${BACKEND_CONTAINER_NAME}=${{ secrets.DOCKER_USER }}/${{ env.BACKEND_IMAGE_NAME }}:${GITHUB_SHA::7}
        
  deploy-frontend: 
    name: Deploy frontend
    runs-on: self-hosted
    needs: test
    container: bitnami/kubectl:latest
    env:
      NAMESPACE: a-cordes
      FRONTEND_IMAGE_NAME: a_cordes_frontend
      FRONTEND_DEPLOYMENT_NAME: a-cordes-frontend
      FRONTEND_CONTAINER_NAME: a-cordes-frontend
    steps:
    - uses: actions/checkout@v3
    - name: Deployment
      run: |
        kubectl -n ${NAMESPACE} set image deployment/${FRONTEND_DEPLOYMENT_NAME} \
          ${FRONTEND_CONTAINER_NAME}=${{ secrets.DOCKER_USER }}/${FRONTEND_IMAGE_NAME}:${GITHUB_SHA::7}
        