name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches: 
      - master

jobs:
  build:
    runs-on: self-hosted
    container: docker:latest
    env:
      BACKEND_IMAGE_NAME: a_cordes_backend
      FRONTEND_IMAGE_NAME: a_cordes_frontend
      TAG: latest
    steps:
    - uses: actions/checkout@v2
    - name: Preparing environment
      run: |
        cd a_cordes
    - name: Login to Docker registry
      run: |
        echo "$DOCKER_USER"
        docker login -u "$DOCKER_USER" -p "$DOCKER_PASSWORD" 
    - name: Backend build and push
      run: |
        docker build --pull -t "${DOCKER_USER}/${BACKEND_IMAGE_NAME}:${TAG}" .
        docker push ${DOCKER_USER}/${BACKEND_IMAGE_NAME}:${TAG}
    - name: Frontend build and push
      run: |
        docker build --pull -t "${DOCKER_USER}/${FRONTENT_IMAGE_NAME}:${TAG}" .
        docker push ${DOCKER_USER}/${FRONTENT_IMAGE_NAME}:${TAG}
        