name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches: 
      - master

.build: &build
  

jobs:
  build:
    runs-on: self-hosted
    container: docker:latest
    env:
      BACKEND_IMAGE_NAME: a_cordes_backend
      FRONTEND_IMAGE_NAME: a_cordes_frontend
      DOCKER_USER: felipebogaertsm
      TAG: latest
    steps:
    - uses: actions/checkout@v2
    - name: Backend build and push
      run: |
        cd a_cordes
        docker login -u "${{ secrets.DOCKER_USER }}" -p "${{ secrets.DOCKER_PASSWORD }}"
        docker build --pull -t "${{ secrets.DOCKER_USER }}/${BACKEND_IMAGE_NAME}:${TAG}" \
          -t "${{ secrets.DOCKER_USER }}/${BACKEND_IMAGE_NAME}:${GITHUB_SHA::7}" .
        docker push ${{ secrets.DOCKER_USER }}/${BACKEND_IMAGE_NAME}:${TAG}
    - name: Frontend build and push
      run: |
        cd frontend
        docker login -u "${{ secrets.DOCKER_USER }}" -p "${{ secrets.DOCKER_PASSWORD }}"
        docker build --pull -t "${{ secrets.DOCKER_USER }}/${FRONTEND_IMAGE_NAME}:${TAG}" \
          -t "${{ secrets.DOCKER_USER }}/${BACKEND_IMAGE_NAME}:${GITHUB_SHA::7}" .
        docker push ${{ secrets.DOCKER_USER }}/${FRONTEND_IMAGE_NAME}:${TAG}
  deploy:
    runs-on: self-hosted
    needs: build
    container: docker:latest
    env:
      NAMESPACE: a-cordes
      BACKEND_IMAGE_NAME: a_cordes_backend
      FRONTEND_IMAGE_NAME: a_cordes_frontend
      BACKEND_DEPLOYMENT_NAME: a-cordes-backend
      FRONTEND_DEPLOYMENT_NAME: a-cordes-frontend
      BACKEND_CONTAINER_NAME: a-cordes-backend
      FRONTEND_CONTAINER_NAME: a-cordes-frontend
    steps:
    - uses: actions/checkout@v2
    - name: Deployment
      run: |
        kubectl -n ${NAMESPACE} set image deployment/${BACKEND_DEPLOYMENT_NAME} \
          ${BACKEND_CONTAINER_NAME}=${{ secrets.DOCKER_USER }}/${BACKEND_IMAGE_NAME}:${GITHUB_SHA::7}
        kubectl -n ${NAMESPACE} set image deployment/${FRONTEND_DEPLOYMENT_NAME} \
          ${FRONTEND_CONTAINER_NAME}=${{ secrets.DOCKER_USER }}/${FRONTEND_IMAGE_NAME}:${GITHUB_SHA::7}
      
        