name: à cordes CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches: 
      - master

env:
  BACKEND_IMAGE_NAME: a_cordes_backend
  FRONTEND_IMAGE_NAME: a_cordes_frontend
  TAG: ${{ github.sha }}
  DOCKER_USER: ${{ secrets.DOCKER_USER }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  KUBECONFIG: ${{ secrets.KUBECONFIG }}

jobs:
  build-backend:
    name: Build backend
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Backend build and push
      run: |
        cd a_cordes
        docker login -u "${{ env.DOCKER_USER }}" -p "${{ env.DOCKER_PASSWORD }}"
        docker build --pull -t "${{ env.DOCKER_USER }}/${{ env.BACKEND_IMAGE_NAME }}:${{ env.TAG }}" .
        docker push ${{ env.DOCKER_USER }}/${{ env.BACKEND_IMAGE_NAME }}:${{ env.TAG }}

  build-frontend:
    name: Build frontend
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Frontend build and push
      run: |
        cd frontend
        docker login -u "${{ env.DOCKER_USER }}" -p "${{ env.DOCKER_PASSWORD }}"
        docker build --pull -t "${{ env.DOCKER_USER }}/${{ env.FRONTEND_IMAGE_NAME }}:${{ env.TAG }}" .
        docker push ${{ env.DOCKER_USER }}/${{ env.FRONTEND_IMAGE_NAME }}:${{ env.TAG }}

  test:
    name: Testing the backend
    runs-on: ubuntu-latest
    needs: 
    - build-backend
    container: 
      image: felipebogaertsm/a_cordes_backend:${{ github.sha }}
      options: --user root
    steps:
    - uses: actions/checkout@v3
    - name: Testing
      run: |
        ls -la
        cd a_cordes
        python3 -m pytest

  deploy:
    name: Deployment using Helm chart
    runs-on: ubuntu-latest
    container: bitnami/kubectl:latest
    steps:
    - uses: actions/checkout@v3
    - uses: azure/k8s-set-context@v2
      with:
        method: kubeconfig
        kubeconfig: ${{ env.KUBECONFIG }}
    - name: Install helm
      run: |
        apt-get install curl
        curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
        chmod 700 get_helm.sh
        ./get_helm.sh
    - name: Upgrade chart
      run: |
        helm upgrade --install -f ./k8s-chart/values.yaml \
          --set backend.image="${{ env.DOCKER_USER }}/${BACKEND_IMAGE_NAME}:${{ env.TAG }}",frontend.image="${{ env.DOCKER_USER }}/${FRONTEND_IMAGE_NAME}:${{ env.TAG }}" \
          --atomic a-cordes-k8s ./k8s-chart
