name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches: 
      - master

jobs:
  build:
    runs-on: self-hosted
    container: docker:latest
    env:
      BACKEND_IMAGE_NAME: a_cordes_backend
      FRONTEND_IMAGE_NAME: a_cordes_frontend
      DOCKER_USER: felipebogaertsm
      TAG: latest
    steps:
    - uses: actions/checkout@v2
    - name: Backend build and push
      run: |
        cd a_cordes
        docker login -u "${{ secrets.DOCKER_USER }}" -p "${{ secrets.DOCKER_PASSWORD }}"
        docker build --pull -t "${{ secrets.DOCKER_USER }}/${BACKEND_IMAGE_NAME}:${TAG}" .
        docker push ${{ secrets.DOCKER_USER }}/${BACKEND_IMAGE_NAME}:${TAG}
    - name: Frontend build and push
      run: |
        cd frontend
        docker login -u "${{ secrets.DOCKER_USER }}" -p "${{ secrets.DOCKER_PASSWORD }}"
        docker build --pull -t "${{ secrets.DOCKER_USER }}/${FRONTEND_IMAGE_NAME}:${TAG}" .
        docker push ${{ secrets.DOCKER_USER }}/${FRONTEND_IMAGE_NAME}:${TAG}
        