apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-runner
  namespace: github-actions
  labels:
    app: github-runner
spec:
  replicas: 3
  selector:
    matchLabels:
      app: github-runner
  template:
    metadata:
      labels:
        app: github-runner
    spec:
      containers:
        - name: github-runner
          image: felipebogaertsm/github-actions-runner@sha256:118fffb33626a0364c4183a406f732a66a27d2dce67f38da51cb01ba7d12914c
          imagePullPolicy: Always
          env:
            - name: GITHUB_OWNER
              valueFrom:
                secretKeyRef:
                  name: github-actions-secrets
                  key: owner
            - name: GITHUB_REPOSITORY
              valueFrom:
                secretKeyRef:
                  name: github-actions-secrets
                  key: repo
            - name: GITHUB_PAT
              valueFrom:
                secretKeyRef:
                  name: github-actions-secrets
                  key: pat
            - name: RUNNER_WORKDIR
              valueFrom:
                secretKeyRef:
                  name: github-actions-secrets
                  key: work_dir
          volumeMounts:
          - name: dockersock
            mountPath: /var/run/docker.sock
          - name: workdir
            mountPath: /tmp/github-runner-a-cordes
      volumes:
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock
      - name: workdir
        hostPath:
          path: /tmp/github-runner-a-cordes
